# ChatGPT App: .csv Analysis

# Complete the Shiny app below as prompted and save as a .R file to 
# submit. When complete, you should be able to upload a .csv, ask 
# questions to ChatGPT about the .csv, then receive a response from
# ChatGPT. 

######################################################################
# load packages and .env
library(shiny)
library(httr)
library(dotenv)
library(readr)
load_dot_env()
######################################################################

######################################################################
# 1. Load your API key from your .env file.
######################################################################

api_key = Sys.getenv("OPENAI_API_KEY")
  
######################################################################
# 2. Build the UI:
#     a. To the sidebar panel, add a fileInput to allow users to upload
#        a file into the app. 
#     b. In the Ask ChatGPT tab, add appropriate labels to the text input 
#        and action button. 
# We’ll come back to the ChatGPT output and dataTableOutput.
######################################################################

# Define UI ----
ui = fluidPage(
  # Add a title panel here,
  
  sidebarLayout(
    sidebarPanel(
      fileInput("file", "Choose CSV File", accept = ".csv"),
    ), 
    mainPanel(
      tabsetPanel(
        type = "tabs",
        tabPanel("Ask ChatGPT",
                 textAreaInput("prompt", label = "Chat with your custom data"),
                 actionButton("submit", label = "Send"),
                 h1(" "),
                 # insert output from ChatGPT here
                 textOutput("chatgpt_response")
                 ),
        tabPanel("Your Data",
                 dataTableOutput("uploaded_data")
                 )
      )
    )
  )
)

######################################################################
# 3. Build the server:
#     a. Change the "..." in the input_file function to the name you gave 
#        your fileInput in question 2a. 
#     b. Find the df_prompt object below.Describe what it does in a comment 
#        above the function. 
#     c. Using the code in slide 20 as your guide, fill in the post request 
#        to ChatGPT, including two lines of content: the first should be the 
#        prompt including the data uploaded by the user, and the second should 
#        be the question or prompt input by the user in the Shiny app.
#     d. Update the "..." in output$chatgpt_response to pull the response from 
#        ChatGPT to the prompt input by the user. Hint: use slide 19 as your 
#        guide, noting that the response in this case is generated by a function
#        we defined in the app. 
######################################################################

# Define server logic ----
server = function(input, output) {
  
  input_file = reactive({
    if (is.null(input$file)) {
      return("")
    }
    
    # actually read the file
    read.csv(file = input$file$datapath)
  })
  
  output$uploaded_data = renderDataTable({
    req(input_file())
    input_file()
  }, options = list(pageLength = 10)
  )
  
  # 3b - replace this comment with your description of what df_prompt does.
  df_prompt = reactive({
    req(input_file)
    # note the use of head() keeping only a few rows
    df_to_text = format_delim(head(input_file()), delim = ",")
    paste("You have been provided this data:", df_to_text)
  })
  
  ask_chatgpt = eventReactive(input$submit, {
      POST(
        # fill in the request to ChatGPT here
        url = "https://api.openai.com/v1/chat/completions",
        add_headers(Authorization = paste("Bearer", api_key)),
        content_type_json(),
        encode = "json",
        body = list(
          model = "gpt-3.5-turbo",
          messages = list(list(role = "user", content = df_prompt()),
                          list(role = "user", content = input$prompt))
        )        
      )
  })

  output$chatgpt_response = renderText({
    req(ask_chatgpt())
    c = content(ask_chatgpt())
    c$choices[[1]]$message$content
  })
    
}

######################################################################
# 4. Revisit the UI:
#     a. The output from ChatGPT (question 2d) is built with a renderText 
#        function. Add the corresponding UI function in line 22 to show the 
#        text output "chatgpt_response". 
#     b. Look for the other output object defined in the server function. 
#        What is it? Replace the final "..." in dataTableOutput  with the name 
#        of this object. (Don’t forget quotes.)
######################################################################

# Run the app ----
shinyApp(ui = ui, server = server)

######################################################################
# 5. Run the app and some sample questions. Do you always get accurate
# responses?
######################################################################

# Not always. I tried to get it tp run regressions for me and compared the results.
# It is quite good however at helping me summarize and do descriptives on the data.

######################################################################
# 6. Describe two or more limitations of this app.
######################################################################

# No code, your comments here. 
# It is unable to do complex actions on the data e.g creating predictive models.
# It is also a bit faulty when doing some calculations. It is clearly best to use it
# as a form factor for high level non detailed Exploratory Data Analysis

######################################################################
# 7. This is a very tiny corner of the world of possibilities with the 
# OpenAI API. Describe another idea or ideas you have for incorporating 
# ChatGPT into analytics in R.
######################################################################

# No code, your comments here. 
# With a redesigned UI available I think we can create a drag and drop predictive model creator.
# Open AI can provide automatic inferences and implications as a starting point for the Analyst
# who uses the App. Think of it as Esquisse but for Modelling.
